


--1

INSERT INTO USUARIO VALUES
('67', 'Antonio', 'Gomez', 20,'M');


INSERT INTO LIBRO (ISBN,TITULO) VALUES
('4A','DON QUIJOTE');

INSERT INTO PRESTAMO (isbn, cod, fecha_ini) VALUES
('4A', '67','07/12/2025');


--2

UPDATE PRESTAMO 
    SET fecha_fin = ADD_MONTHS(fecha_ini,5)
    WHERE cod = '67';
    
--3

SELECT *
FROM PRESTAMO
WHERE FECHA_FIN < '1/11/2016';

DELETE FROM PRESTAMO
WHERE FECHA_FIN < '1/11/2016';

--4
INSERT INTO USUARIO (COD, NOMBRE, APELLIDO, EDAD) VALUES
('68', 'Jon', 'Alkorta',10);
--salta la restriccion de control de edad porque es menor que 14 años el usuario que se quiere dar de alta

--5

ALTER TABLE CLASELIBRO
DROP CONSTRAINT CH_clases;

INSERT INTO CLASELIBRO VALUES
('F', 15);

INSERT INTO LIBRO (ISBN,CLASE, TITULO, EDITORIAL) VALUES
('1FBD','F', 'FICHEROS Y BASES DE DATOS', 'ANAYA');

INSERT INTO LIBRO (ISBN,CLASE, TITULO, EDITORIAL) VALUES
('2FBD', 'F','FICHEROS Y BASES DE DATOS II', 'ANAYA');

INSERT INTO LIBRO (ISBN,CLASE, TITULO, EDITORIAL) VALUES
('3FBD', 'F','FICHEROS Y BASES DE DATOS III', 'ANAYA');

--6

UPDATE CLASELIBRO
SET TIEMPO = TIEMPO + 15
WHERE CLASE = 'B';

--7

SELECT COD
FROM USUARIO
WHERE NOMBRE = 'Antonio' AND APELLIDO= 'Gomez';

DELETE FROM PRESTAMO
WHERE COD = '67';


DELETE FROM USUARIO
WHERE COD = '67';

--8

INSERT INTO USUARIO VALUES
('67', 'Antonio', 'Gomez', 20,'M');

SELECT *
FROM USUARIO
WHERE (NOMBRE ='Rosa' AND APELLIDO= 'PEREZ') AND (NOMBRE='Lucas' AND APELLIDO='PEREZ');

INSERT INTO USUARIO (COD, NOMBRE, APELLIDO) VALUES
('68','Rosa', 'PEREZ');

INSERT INTO USUARIO (COD, NOMBRE, APELLIDO) VALUES
('69','Lucas', 'PEREZ');

INSERT INTO PRESTAMO VALUES
('1FBD','68', '27/10/2020','11/11/2020');
INSERT INTO PRESTAMO VALUES
('2FBD','69', '27/10/2020','11/11/2020');
INSERT INTO PRESTAMO VALUES
('3FBD','67', '27/10/2020','11/11/2020');

--9

UPDATE PRESTAMO
SET FECHA_FIN =SYSDATE
WHERE COD IN ('67','68','69');

--10

select * 
from prestamo
where fecha_fin <SYSDATE;

DELETE FROM PRESTAMO
WHERE FECHA_FIN < SYSDATE;

--11

INSERT INTO USUARIO (COD, NOMBRE, APELLIDO, EDAD) VALUES
('70','Alberto', 'VIZCAY', 22);

INSERT INTO USUARIO (COD, NOMBRE, APELLIDO, EDAD) VALUES
('71','Pedro', 'AGOS', 23);

INSERT INTO USUARIO (COD, NOMBRE, APELLIDO, EDAD) VALUES
('72','Luis', 'ALONSO', 22);

INSERT INTO USUARIO (COD, NOMBRE, APELLIDO, EDAD) VALUES
('73','Juan', 'ARRONDO', 65);

--12

INSERT INTO LIBRO VALUES
('5D', 'A','Algebra 5', 'Esain', 'mcgraw-hill');
--problema con PK_libro
SELECT ISBN
FROM LIBRO
WHERE ISBN='20D';
--ya existe uno asi 
INSERT INTO LIBRO VALUES
('6D', 'B','Calculo 1A', 'Urrutia', 'mcgraw-hill');

INSERT INTO LIBRO VALUES
('7D', 'C','Calculo 2B', 'kricke', 'mcgraw-hill');

INSERT INTO LIBRO VALUES
('20D', 'B','Inteligencia Artificial I', 'Urtasun', 'mcgraw-hill');
--tuve que cambiar el titulo porque ya habia una que se llamaba asi.

--solucion posible borrar todos los anteriores con ese ISBN
DELETE FROM LIBRO
WHERE ISBN IN ('5A','6C','7A','20A');
--bloquea una FK, entonces asignamos distintos ISBN

--13

INSERT INTO PRESTAMO(ISBN, COD, FECHA_INI) VALUES
('20A','2','15/11/2020'); --HECHO

INSERT INTO PRESTAMO(ISBN, COD, FECHA_INI, FECHA_FIN) VALUES
('19A','5','05/11/2020', '10/11/2020'); --NO EXISTE USUARIO

INSERT INTO PRESTAMO(ISBN, COD, FECHA_INI, FECHA_FIN) VALUES
('5A','1','06/09/2020','07/09/2020');

INSERT INTO PRESTAMO(ISBN, COD, FECHA_INI) VALUES
('6C','2','07/09/2020');

INSERT INTO PRESTAMO(ISBN, COD, FECHA_INI, FECHA_FIN) VALUES
('7A','3','08/09/2020','11/09/2020');

INSERT INTO PRESTAMO(ISBN, COD, FECHA_INI, FECHA_FIN) VALUES
('5A','4','09/09/2020','13/09/2020');

--14

UPDATE PRESTAMO
SET FECHA_FIN = SYSDATE
WHERE ISBN IN ('20A', '6C') AND COD = '2';

--15
--NO TENGO NI IDEA A QUE SE REFIERE.





