

--1

SELECT DISTINCT EDITORIAL, COUNT(*)VOLUMENES
FROM LIBRO
GROUP BY EDITORIAL
ORDER BY 2 DESC;

--2

SELECT DISTINCT L.EDITORIAL, COUNT(*)PRESTAMOS
FROM LIBRO L, PRESTAMO P
WHERE P.ISBN = L.ISBN
GROUP BY EDITORIAL
ORDER BY 2 DESC;

--3

SELECT COUNT(*)TOTAL_PRESTAMOS
FROM PRESTAMO;

--4

SELECT U.COD, U.NOMBRE, U.EDAD, COUNT(*)
FROM USUARIO U, PRESTAMO P
WHERE U.COD = P.COD AND U.EDAD BETWEEN 20 AND 30
HAVING COUNT(*) >1
GROUP BY U.COD, U.NOMBRE, U.EDAD
ORDER BY U.COD ASC, 4 ASC;


--5

SELECT U.COD, U.NOMBRE, U.APELLIDO, L.EDITORIAL, COUNT(*)PRESTAMOS
FROM USUARIO U, LIBRO L, PRESTAMO P
WHERE U.COD = P.COD AND L.ISBN = P.ISBN
HAVING COUNT(*) > 2
GROUP BY U.COD, U.NOMBRE, U.APELLIDO,L.EDITORIAL;

--6

SELECT L.ISBN, L.TITULO, L.AUTOR, P.FECHA_INI, P.FECHA_FIN
FROM LIBRO L, PRESTAMO P
WHERE L.ISBN = P.ISBN AND P.FECHA_FIN IS NULL;

--7
SELECT L.ISBN
FROM LIBRO L, PRESTAMO P
WHERE L.ISBN = P.ISBN AND P.FECHA_FIN IS NULL
HAVING COUNT(*)>1
GROUP BY L.ISBN;

SELECT L.ISBN, P.COD, P.FECHA_INI, P.FECHA_FIN
FROM LIBRO L, PRESTAMO P
WHERE L.ISBN = P.ISBN AND P.FECHA_FIN IS NULL AND L.ISBN ='6C';

DELETE FROM PRESTAMO
WHERE ISBN = '6C' AND FECHA_INI != '04/07/2020';

--No lo hice 100% bien, creo que borre uno que no debia JAJA

--8

SELECT U.COD, U.NOMBRE, U.APELLIDO, L.TITULO, C.TIEMPO, (P.FECHA_FIN - P.FECHA_INI)DIAS_PRESTAMO, ((P.FECHA_FIN-P.FECHA_INI)-C.TIEMPO)EXCEDIDOS
FROM USUARIO U, LIBRO L, CLASELIBRO C, PRESTAMO P
WHERE U.COD = P.COD AND P.ISBN = L.ISBN AND L.CLASE = C.CLASE AND P.FECHA_FIN IS NOT NULL
ORDER BY 5 ASC, 6 DESC, 7 DESC;

--9

SELECT U.COD, U.NOMBRE, U.APELLIDO, L.TITULO, C.TIEMPO, P.FECHA_INI,SYSDATE,TRUNC((SYSDATE-P.FECHA_INI),0)DIAS_PRESTAMO, TRUNC(((SYSDATE-P.FECHA_INI)-C.TIEMPO),0)EXCEDIDOS
FROM USUARIO U, LIBRO L, CLASELIBRO C, PRESTAMO P
WHERE U.COD = P.COD AND P.ISBN = L.ISBN AND L.CLASE = C.CLASE AND P.FECHA_FIN IS NULL
ORDER BY 5 ASC, 6 DESC, 7 DESC;

--10

SELECT COUNT(*)AS AUTORES
FROM LIBRO
WHERE LENGTH(AUTOR) = 5;

--11

SELECT L.EDITORIAL, SUM(C.TIEMPO)
FROM LIBRO L, CLASELIBRO C
WHERE L.CLASE = C.CLASE
GROUP BY L.EDITORIAL
ORDER BY 2 ASC;

--12


SELECT DISTINCT L.ISBN, L.TITULO
FROM LIBRO L, PRESTAMO P, PRESTAMO P2
WHERE P.COD != P2.COD AND P.ISBN = L.ISBN AND P2.ISBN = L.ISBN;

--BORRE SIN QUERER CALCULO 1A JAJA
--13

SELECT UNIQUE P.COD, P.ISBN, P2.ISBN
FROM PRESTAMO P, PRESTAMO P2
WHERE P.COD = P2.COD AND P.FECHA_FIN IS NULL AND P2.FECHA_FIN IS NULL AND P.ISBN < P2.ISBN;




