
--practica1.2


--1

SELECT D.CODIGO, D.NOMBRE, A.CODIGO, A.NOMBRE
FROM DEPARTAMENTOS D, AREAS A
WHERE D.CODIGO = A.DEPARTAMENTO
ORDER BY D.CODIGO, A.CODIGO ASC;

--2

SELECT D.ID, D.CURSO, D.CLASE, D.GRUPO, D.SIGLAS, D.PROFESOR, D.LOCAL, D.DIA, D.HORA, D.PERIODICIDAD
FROM DOCENCIA D, LOCALES L
WHERE D.LOCAL = L.CODIGO AND L.CAPACIDAD >100 AND D.CURSO = 1;

--3

SELECT DISTINCT P.CODIGO, TRIM(NVL(P.APELLIDO1,'') || ' ' ||
    NVL(P.APELLIDO2,'') || ', ' ||
    NVL(P.NOMBRE_PILA,'') ) AS NOMBRE_Y_APELLIDOS
FROM PROFESORES P, DOCENCIA D, ASIGNATURAS A
WHERE P.CODIGO = D.PROFESOR AND D.SIGLAS = A.SIGLAS AND A.NOMBRE LIKE 'Bases de Datos'
ORDER BY 2 ASC;

--4

SELECT G.CURSO AS C, G.CLASE AS C, G.CODIGO AS COD, G.NOMBRE, D.ID, D.CURSO AS C,
    D.CLASE AS C, D.GRUPO AS GRU, D.SIGLAS, D.PROFESOR, D.LOCAL, D.DIA AS D, D.HORA, D.PERIODICIDAD
FROM GRUPOS G, DOCENCIA D, ASIGNATURAS A
WHERE G.CURSO = D.CURSO AND D.CLASE = G.CLASE AND D.GRUPO = G.CODIGO AND A.SIGLAS = D.SIGLAS AND A.NOMBRE LIKE 'Bases de Datos';

--5

SELECT P.CODIGO, P.NOMBRE_PILA, A.NOMBRE, A.ALUMNOS
FROM PROFESORES P, ASIGNATURAS A, DOCENCIA D
WHERE P.CODIGO = D.PROFESOR AND D.SIGLAS = A.SIGLAS
GROUP BY P.CODIGO, P.NOMBRE_PILA, A.NOMBRE, A.ALUMNOS;

--6

SELECT DISTINCT TRIM(NVL(D.NOMBRE,'') || '(' || NVL(D.CODIGO,'') || ')' ) AS NOMBRE_DEPARTAMENTO, G.NOMBRE
FROM DEPARTAMENTOS D, GRUPOS G, AREAS A, PROFESORES P, DOCENCIA DOC
WHERE D.CODIGO = A.DEPARTAMENTO AND A.CODIGO = P.AREA AND 
    P.CODIGO = DOC.PROFESOR AND DOC.CURSO = G.CURSO AND 
    DOC.CLASE = G.CLASE AND DOC.GRUPO = G.CODIGO
ORDER BY 2 DESC;

--7

SELECT DISTINCT A.SIGLAS, A.NOMBRE, DOC.DIA, DOC.HORA, L.CODIGO, L.NOMBRE
FROM ASIGNATURAS A, DOCENCIA DOC, LOCALES L
WHERE A.SIGLAS = DOC.SIGLAS AND DOC.LOCAL = L.CODIGO AND (A.ANUALIDAD = NULL OR A.SIGLAS IN ('ACo','BDa','DES','Eco','Fis-G'))
ORDER BY A.SIGLAS;

--8
SELECT DISTINCT A.NOMBRE, G.NOMBRE, ROUND(A.ALUMNOS/GRUPOS_PRACTICA,2) AS ALUMNOSXGRUPO
FROM ASIGNATURAS A, GRUPOS G, DOCENCIA D
WHERE A.SIGLAS = D.SIGLAS AND D.CURSO = G.CURSO AND D.CLASE = G.CLASE AND
    D.GRUPO = G.CODIGO AND D.CLASE LIKE 'P' AND (D.HORA NOT BETWEEN 11.3 AND 19.3)
ORDER BY 3 DESC, 1,2 ASC;

