ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER practicas IDENTIFIED BY "kakafusionadaconkaka"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO practicas;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO practicas;
