
--3

SELECT CODHOSP, NOMHOSP, NUMEMP
FROM HOSPITAL
WHERE CIUDAD = 'Pamplona';

--4
SELECT COUNT(CODHOSP)TOTAL
FROM HOSPITAL;

--5
SELECT COUNT(CODHOSP)TOTAL
FROM HOSPITAL
WHERE NUMEMP >4;

--6

SELECT *
FROM EMPLEADO
ORDER BY CUALIFICACION;

--7

SELECT COUNT(*)TOTAL_AUXILIARES
FROM EMPLEADO
WHERE CUALIFICACION = 'AUXILIAR';

--8
SELECT COUNT(E.DNI)TOTAL_AUX_DEP3
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.CUALIFICACION = 'AUXILIAR' AND D.CODDEPT = 'D3' AND E.DEPAR = D.CODDEPT;


--9
SELECT H.NOMHOSP, COUNT(E.DNI)TOTAL_AUX_DEP3
FROM EMPLEADO E, DEPHOSPITAL D, HOSPITAL H, TRABAJA T
WHERE E.CUALIFICACION = 'AUXILIAR' AND D.CODDEPT = 'D3' AND E.DEPAR = D.CODDEPT
    AND H.CODHOSP = T.CODHOSP AND T.DNI = E.DNI
GROUP BY H.NOMHOSP;

--10

CREATE VIEW DOCTORES_PEDIATRIA
AS(
    SELECT E.DNI, E.NOMBRE, D.CODDEPT
    FROM EMPLEADO E, DEPHOSPITAL D
    WHERE E.DEPAR = D.CODDEPT AND E.CUALIFICACION = 'DOCTOR' 
        AND D.NOMDEPT = 'PEDIATRIA');
        
SELECT * FROM DOCTORES_PEDIATRIA;

--11
SELECT E.DNI, E.AP1, E.SUELDO, H.CODHOSP
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE H.CODHOSP = T.CODHOSP AND T.DNI = E.DNI;


--12

SELECT E.DNI, E.AP1, E.SUELDO, COUNT(H.CODHOSP)
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE H.CODHOSP = T.CODHOSP AND T.DNI = E.DNI
GROUP BY E.DNI, E.AP1, E.SUELDO
ORDER BY 4 DESC;

--13

SELECT COUNT(*)INGRESOS
FROM INGRESOS
WHERE FECHA > TO_DATE('01/01/2019','DD/MM/YYYY');

--14
CREATE VIEW INGRESOS_PEDIATRIA
AS(
    SELECT D.NOMDEPT, COUNT(*)INGRESOS
    FROM DEPHOSPITAL D, INGRESOS I, EMPLEADO E
    WHERE D.NOMDEPT = 'PEDIATRIA' AND I.DNI = E.DNI AND E.DEPAR = D.CODDEPT AND I.FECHA > TO_DATE('01/01/2019', 'DD/MM/YYYY')
    GROUP BY D.NOMDEPT
);

SELECT * FROM INGRESOS_PEDIATRIA;

--15

SELECT I.HISTORIAL, I.DNI, I.CODHOSP, I.FECHA, H.NOMHOSP, E.AP1
FROM INGRESOS I, HOSPITAL H, EMPLEADO E
WHERE I.DNI = E.DNI AND I.CODHOSP = H.CODHOSP;


--16

SELECT SUM(NUMEMP)NUM_EMPLEADOS
FROM HOSPITAL;

--17

SELECT CODHOSP, SUM(NUMEMP)
FROM HOSPITAL
GROUP BY CODHOSP;

--18

SELECT MAX(SUELDO), MIN(SUELDO), TRUNC(AVG(SUELDO),2)
FROM EMPLEADO;

--19

SELECT MAX(E.SUELDO), MIN(E.SUELDO), TRUNC(AVG(E.SUELDO),2)
FROM EMPLEADO E, PACIENTE P, INGRESOS I
WHERE E.DNI = I.DNI AND I.HISTORIAL = P.HISTORIAL AND P.NOMBRE = 'Garc�a';

--21

SELECT D.CODDEPT,AVG(E.SUELDO)
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR = D.CODDEPT
GROUP BY D.CODDEPT;

--22

SELECT D.CODDEPT,AVG(E.SUELDO)
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR = D.CODDEPT
GROUP BY D.CODDEPT
HAVING AVG(E.SUELDO) >400;


--23

SELECT DISTINCT E.CUALIFICACION, SUM(E.SUELDO)
FROM EMPLEADO E
GROUP BY E.CUALIFICACION
ORDER BY SUM(E.SUELDO) DESC;

--24

SELECT H.NOMHOSP, SUM(H.NUMEMP)
FROM HOSPITAL H
GROUP BY H.NOMHOSP;

--25

SELECT DISTINCT E.DNI
FROM EMPLEADO E, INGRESOS I
WHERE I.DNI = E.DNI;

--26

SELECT I.HISTORIAL, I.FECHA, I.CODHOSP, H.NOMHOSP, E.NOMBRE, E.DIRECCION, D.NOMDEPT
FROM INGRESOS I, HOSPITAL H, EMPLEADO E, DEPHOSPITAL D
WHERE I.DNI = E.DNI AND I.CODHOSP = H.CODHOSP AND E.DEPAR = D.CODDEPT;

--27

SELECT H.CIUDAD, COUNT(*)
FROM HOSPITAL H, INGRESOS I
WHERE I.CODHOSP = H.CODHOSP
GROUP BY H.CIUDAD;

--28

SELECT D.NOMDEPT, COUNT(*)
FROM DEPHOSPITAL D, INGRESOS I, EMPLEADO E
WHERE I.DNI = E.DNI AND E.DEPAR = D.CODDEPT AND I.FECHA > TO_DATE('31/12/2018','DD/MM/YYYY')
GROUP BY D.NOMDEPT;

--29

SELECT H.CIUDAD, D.NOMDEPT, COUNT(*)
FROM DEPHOSPITAL D, INGRESOS I, EMPLEADO E, HOSPITAL H
WHERE I.DNI = E.DNI AND E.DEPAR = D.CODDEPT AND I.FECHA > TO_DATE('31/12/2018','DD/MM/YYYY') AND H.CODHOSP = I.CODHOSP
GROUP BY H.CIUDAD, D.NOMDEPT;


--30
CREATE VIEW PACIENTE_VARIOS_INGRESOS
AS(
    SELECT P.NOMBRE, COUNT(*)VISITAS
    FROM PACIENTE P, INGRESOS I
    WHERE I.HISTORIAL = P.HISTORIAL
    GROUP BY P.NOMBRE
    HAVING COUNT(*) > 2
);

SELECT * FROM PACIENTE_VARIOS_INGRESOS;

