--19

SELECT G.CURSO, MAX(A.ALUMNOS), MIN(A.ALUMNOS), ROUND(AVG(A.ALUMNOS),1)
FROM GRUPOS G, ASIGNATURAS A, DOCENCIA D
WHERE D.SIGLAS = A.SIGLAS AND D.CURSO = G.CURSO AND D.CLASE = G.CLASE
    AND D.GRUPO = G.CODIGO
GROUP BY G.CURSO
ORDER BY 1 ASC;

--20

SELECT L.NOMBRE, L.EDIFICIO, MAX(G.CURSO)"CURSO_MAS_ALTO"
FROM LOCALES L, GRUPOS G, DOCENCIA D
WHERE D.CURSO = G.CURSO AND D.CLASE = G.CLASE AND D.GRUPO = G.CODIGO
    AND D.LOCAL = L.CODIGO
GROUP BY L.NOMBRE, L.EDIFICIO;


--21

SELECT A.NOMBRE, D.DIA, COUNT(DISTINCT P.CODIGO)"PROFESORES_NO_TIEMPO_LIMITADO"
FROM ASIGNATURAS A, DOCENCIA D, PROFESORES P
WHERE P.DEDICACION != 'TC' AND A.SIGLAS = D.SIGLAS 
    AND D.PROFESOR = P.CODIGO 
HAVING COUNT(DISTINCT P.CODIGO) > 1
GROUP BY A.NOMBRE, D.DIA;


--22

SELECT (A.NOMBRE || '    (' || A.SIGLAS || ') ')"ASIGNATURA", AVG(A.ALUMNOS)"ALUMNOS_POR_CLASE"
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS = D.SIGLAS
GROUP BY A.NOMBRE, A.SIGLAS;

--23

SELECT G.NOMBRE, COUNT(DISTINCT P.CODIGO)
FROM GRUPOS G, PROFESORES P, DOCENCIA D
WHERE D.CURSO = G.CURSO AND D.CLASE = G.CLASE AND D.GRUPO = G.CODIGO
    AND D.PROFESOR = P.CODIGO
GROUP BY G.NOMBRE;

--24

SELECT G.NOMBRE
FROM GRUPOS G, PROFESORES P, DOCENCIA D
WHERE D.CURSO = G.CURSO AND D.CLASE = G.CLASE AND D.GRUPO = G.CODIGO
    AND D.PROFESOR = P.CODIGO
HAVING COUNT(DISTINCT P.CODIGO)=1
GROUP BY G.NOMBRE;

--25

SELECT (P.APELLIDO1 || '  ' ||P.APELLIDO2 || '  ' || P.NOMBRE_PILA)NOMBRE_APELLIDOS, COUNT(A.SIGLAS)CUENTA_ASIGNATURAS
FROM PROFESORES P, ASIGNATURAS A, DOCENCIA D
WHERE D.PROFESOR = P.CODIGO AND A.SIGLAS = D.SIGLAS
GROUP BY P.APELLIDO1, P.APELLIDO2, P.NOMBRE_PILA
ORDER BY P.APELLIDO1 ASC, P.APELLIDO2 ASC, P.NOMBRE_PILA ASC;

--26
SELECT (P.APELLIDO1 || '  ' ||P.APELLIDO2 || '  ' || P.NOMBRE_PILA)NOMBRE_APELLIDOS
FROM PROFESORES P, ASIGNATURAS A, DOCENCIA D
WHERE D.PROFESOR = P.CODIGO AND A.SIGLAS = D.SIGLAS
GROUP BY P.APELLIDO1, P.APELLIDO2, P.NOMBRE_PILA
HAVING COUNT(DISTINCT A.SIGLAS)!=1;

--27


SELECT L.NOMBRE AS "AULA", L.EDIFICIO, 
    (L.CAPACIDAD - A.ALUMNOS/COUNT(D.ID))DIFERENCIA_ALUMNOS_X_CLASE, 
    A.NOMBRE AS "ASIGNATURA", COUNT(A.CLASE) 
FROM LOCALES L, ASIGNATURAS A,DOCENCIA D
WHERE L.CODIGO = D.LOCAL AND A.SIGLAS = D.SIGLAS
GROUP BY L.NOMBRE, L.EDIFICIO, A.NOMBRE, L.CAPACIDAD, A.ALUMNOS
HAVING (L.CAPACIDAD - A.ALUMNOS/COUNT(D.ID)) <=0;


