

--1

SELECT COUNT(SIGLAS) AS "NUMASIGNATURAS"
FROM ASIGNATURAS;

--2
SELECT COUNT(SIGLAS)
FROM ASIGNATURAS
WHERE ANUALIDAD LIKE 'A';

--3
SELECT MAX(ALUMNOS) "MAXALUMNOS"
FROM ASIGNATURAS;

--4
SELECT AVG(ALUMNOS)"MEDIAALUMNOS"
FROM ASIGNATURAS;

--5
SELECT SUM(ALUMNOS)"SUMAALUMNOS"
FROM ASIGNATURAS;

--6
SELECT P.CODIGO AS "PROFESOR", COUNT(D.ID) AS "DOCENCIA"
FROM PROFESORES P, DOCENCIA D
WHERE P.CODIGO = D.PROFESOR
GROUP BY P.CODIGO
ORDER BY 1 ASC;

--7
SELECT P.CODIGO AS "PROFESOR", COUNT(D.ID) AS "DOCENCIA"
FROM PROFESORES P, DOCENCIA D
WHERE P.CODIGO = D.PROFESOR
GROUP BY P.CODIGO
HAVING COUNT(D.ID) > 10
ORDER BY 1 ASC;

--8

SELECT SUM(A.horas_teoria) AS TOTALHORASTEORIA,
  SUM(A.horas_practica) AS TOTALHORASPRACTICA
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS = D.SIGLAS;

--9
SELECT SUM(A.HORAS_TEORIA)"TOTALHORASTEORIA", SUM(A.HORAS_PRACTICA)"TOTALHORASPRACTICAS"
FROM ASIGNATURAS A, PROFESORES P, DOCENCIA D
WHERE A.ANUALIDAD LIKE 'A' AND P.CODIGO >30 
    AND A.SIGLAS = D.SIGLAS AND D.PROFESOR = P.CODIGO;

--10
SELECT COUNT(A.SIGLAS)"NUMASIG",TRUNC(AVG(A.HORAS_PRACTICA),4)"MEDIAHORASPRACTICA"
FROM ASIGNATURAS A, PROFESORES P, DOCENCIA D
WHERE A.SIGLAS = D.SIGLAS AND D.PROFESOR = P.CODIGO AND P.CODIGO >30 AND A.ANUALIDAD LIKE 'A';

--11
SELECT MAX(CAPACIDAD)
FROM LOCALES;

--12
SELECT MAX(L.CAPACIDAD)
FROM LOCALES L, ASIGNATURAS A, DOCENCIA D
WHERE A.HORAS_PRACTICA != 0 AND D.SIGLAS = A.SIGLAS AND D.LOCAL = L.CODIGO;


--13
SELECT COUNT(DISTINCT CODIGO)"LOCALES1"
FROM LOCALES
WHERE SITUACION LIKE 'Planta Primera%';

--14
SELECT SITUACION, COUNT(CODIGO)
FROM LOCALES
GROUP BY SITUACION;

--15
SELECT DIA, MIN(HORA), MAX(HORA)
FROM DOCENCIA
GROUP BY DIA;

--16
SELECT ANUALIDAD, COUNT(SIGLAS), AVG(CREDITOS), MIN(ALUMNOS)
FROM ASIGNATURAS
WHERE ANUALIDAD != 'A' OR ANUALIDAD IS NULL
GROUP BY ANUALIDAD;

--17

SELECT A.SIGLAS, A.NOMBRE
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS = D.SIGLAS
HAVING COUNT(A.SIGLAS) BETWEEN 10 AND 20
GROUP BY A.SIGLAS, A.NOMBRE
ORDER BY A.NOMBRE ASC;

--18

SELECT D.HORA, COUNT(D.DIA)"NUMDIAS"
FROM DOCENCIA D, ASIGNATURAS A
WHERE A.SIGLAS = D.SIGLAS AND A.NOMBRE = 'Algebra'
HAVING COUNT(D.DIA) >= 2
GROUP BY HORA;



