

CREATE TABLE DEPARTAMENTO(
    COD_DEP VARCHAR2(4),
    NOM_DEP VARCHAR2(15) NOT NULL,
    JEFE VARCHAR2(5),
    FECHA_JEFE DATE,
    
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEP),
    CONSTRAINT UNICA_DEPARTAMENTO UNIQUE (NOM_DEP)
);

--OMITIMOS EL FK DE MOMENTO


CREATE TABLE EMPLEADO(
    COD_EMP VARCHAR2(5),
    SUPERVISOR VARCHAR2(5),
    NOMBRE VARCHAR2(15),
    APELLIDO VARCHAR2(15) NOT NULL,
    FECHA_NCTO DATE,
    GENERO VARCHAR2(1) DEFAULT 'M',
    SALARIO NUMBER,
    COD_DEP VARCHAR2(4),
    
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (COD_EMP),
    CONSTRAINT FK2_EMPLEADO FOREIGN KEY (COD_EMP) REFERENCES DEPARTAMENTO(COD_DEP),
    CONSTRAINT FK1_EMPLEADO FOREIGN KEY (SUPERVISOR) REFERENCES EMPLEADO(COD_EMP),
    CONSTRAINT CH_EMPLEADO CHECK (GENERO IN ('V','M'))
);

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT FK_DEPARTAMENTO
FOREIGN KEY (JEFE) REFERENCES EMPLEADO(COD_EMP);

CREATE TABLE LOCALIZACIONES(
    COD_DEP VARCHAR2(4),
    LOCALIZA VARCHAR2(2),
    
    CONSTRAINT PK_LOCALIZACIONES PRIMARY KEY (COD_DEP, LOCALIZA),
    CONSTRAINT FK_LOCALIZACIONES FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE PROYECTO(
    NUM_PROY NUMBER,
    NOM_PROY VARCHAR2(15),
    COD_DEP VARCHAR2(4),
    LOCALIZA VARCHAR2(2),
    
    CONSTRAINT PK_PROYECTO PRIMARY KEY (NUM_PROY),
    CONSTRAINT UNICA_PROYECTO UNIQUE (NOM_PROY),
    CONSTRAINT FK_PROYECTO FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE TRABAJA(
    COD_EMP VARCHAR2(5),
    NUM_PROY NUMBER,
    HORAS NUMBER,
    
    CONSTRAINT PK_TRABAJA PRIMARY KEY (COD_EMP, NUM_PROY),
    CONSTRAINT FK1_TRABAJA FOREIGN KEY (COD_EMP) REFERENCES EMPLEADO(COD_EMP),
    CONSTRAINT FK2_TRABAJA FOREIGN KEY (NUM_PROY) REFERENCES PROYECTO(NUM_PROY)
);

CREATE TABLE DEPENDIENTE(
    NOMBRE VARCHAR2(10),
    COD_EMP VARCHAR2(5),
    FECHA_NCTO DATE,
    PARENTESCO VARCHAR2(15),
    GENERO VARCHAR2(1) DEFAULT 'M',
    
    CONSTRAINT PK_DEPENDIENTE PRIMARY KEY (NOMBRE, COD_EMP),
    CONSTRAINT FK_DEPENDIENTE FOREIGN KEY (COD_EMP) REFERENCES EMPLEADO(COD_EMP),
    CONSTRAINT CH_GENERO_DEP CHECK (GENERO IN ('M','V'))
);


ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY';