

--1

ALTER TABLE DEPENDIENTE ADD
CONSTRAINT CK_PARENTESCO_DEPENDIENTE 
CHECK (PARENTESCO IN ('CONYUGE','DESCENDIENTE','ASCENDIENTE'));

--2

UPDATE EMPLEADO SET COD_EMP = '0013'
WHERE NOMBRE = 'PEDRO' AND APELLIDO ='PEREZ';

--3

ALTER TABLE EMPLEADO DISABLE CONSTRAINT FK1_EMPLEADO;
ALTER TABLE DEPARTAMENTO DISABLE CONSTRAINT FK_DEPARTAMENTO;
ALTER TABLE TRABAJA DISABLE CONSTRAINT FK1_TRABAJA;
ALTER TABLE DEPENDIENTE DISABLE CONSTRAINT FK_DEPENDIENTE;


UPDATE EMPLEADO SET COD_EMP ='0013'
WHERE NOMBRE='PEDRO' AND APELLIDO= 'PEREZ';

UPDATE DEPARTAMENTO SET JEFE = '0013'
WHERE JEFE = '0001';

UPDATE TRABAJA SET COD_EMP='0013'
WHERE COD_EMP='0001';

UPDATE DEPENDIENTE SET COD_EMP = '0013'
WHERE COD_EMP = '0001';

UPDATE EMPLEADO SET SUPERVISOR ='0013'
WHERE SUPERVISOR = '0001';

ALTER TABLE EMPLEADO ENABLE CONSTRAINT FK1_EMPLEADO;
ALTER TABLE TRABAJA ENABLE CONSTRAINT FK1_TRABAJA;
ALTER TABLE DEPARTAMENTO ENABLE CONSTRAINT FK_DEPARTAMENTO;
ALTER TABLE DEPENDIENTE ENABLE CONSTRAINT FK_DEPENDIENTE;

--4

ALTER TABLE DEPENDIENTE DROP CONSTRAINT FK_DEPENDIENTE;

ALTER TABLE DEPENDIENTE ADD
CONSTRAINT FK_DEPENDIENTE FOREIGN KEY (COD_EMP) 
REFERENCES EMPLEADO(COD_EMP) ON DELETE CASCADE;

ALTER TABLE DEPARTAMENTO DROP CONSTRAINT FK_DEPARTAMENTO;

ALTER TABLE DEPARTAMENTO ADD
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (JEFE)
REFERENCES EMPLEADO(COD_EMP) ON DELETE CASCADE;

ALTER TABLE TRABAJA DROP CONSTRAINT FK1_TRABAJA;

ALTER TABLE TRABAJA 
ADD CONSTRAINT FK1_TRABAJA 
FOREIGN KEY (COD_EMP) REFERENCES EMPLEADO(COD_EMP) 
ON DELETE CASCADE;

ALTER TABLE EMPLEADO DROP CONSTRAINT FK1_EMPLEADO;

ALTER TABLE EMPLEADO 
ADD CONSTRAINT FK1_EMPLEADO 
FOREIGN KEY (SUPERVISOR) REFERENCES EMPLEADO(COD_EMP) 
ON DELETE SET NULL;


DELETE FROM EMPLEADO 
WHERE COD_EMP = '1001';

--5

ALTER TABLE LOCALIZACIONES RENAME TO ESPACIOS;

--6

INSERT INTO DEPARTAMENTO VALUES('013', 'FORMACION', '0013', NULL);

--7

UPDATE DEPARTAMENTO SET FECHA_JEFE = SYSDATE
WHERE FECHA_JEFE IS NULL;

--8

ALTER TABLE DEPENDIENTE DROP CONSTRAINT PK_DEPENDIENTE;

ALTER TABLE DEPENDIENTE ADD
CONSTRAINT PK_DEPENDIENTE PRIMARY KEY (COD_EMP, NOMBRE, FECHA_NCTO);

--Es muy improbable que tengan el mismo nombre y que ademas hayan nacido el mismo dia

--9

ALTER TABLE DEPARTAMENTO ADD (AC NUMBER DEFAULT 0);

UPDATE DEPARTAMENTO SET AC = 1
WHERE COD_DEP IN (SELECT D.COD_DEP
                FROM DEPARTAMENTO D, TRABAJA T, PROYECTO P
                WHERE  D.COD_DEP = P.COD_DEP
                    AND T.NUM_PROY  = P.NUM_PROY
                GROUP BY D.COD_DEP
                HAVING SUM(T.HORAS) >700);
                
--10

UPDATE EMPLEADO SET SALARIO = SALARIO *1.15
WHERE COD_EMP IN (SELECT SUPERVISOR
                FROM EMPLEADO 
                WHERE SUPERVISOR IS NOT NULL
                GROUP BY SUPERVISOR
                HAVING COUNT(*) > 2);
                
--11

ALTER TABLE ESPACIOS RENAME TO LOCALIZA;

ALTER TABLE PROYECTO ADD
CONSTRAINT FK2_PROYECTO FOREIGN KEY (COD_DEP,LOCALIZA) REFERENCES LOCALIZA (COD_DEP, LOCALIZA);

--12

UPDATE TRABAJA SET HORAS =180
WHERE HORAS >180;

ALTER TABLE TRABAJA ADD
CONSTRAINT CK_HORAS_TRABAJA CHECK (HORAS <=180);

--13

ALTER TABLE EMPLEADO MODIFY (SALARIO DEFAULT 100);

--14

CREATE TABLE SUPERVISORES(
    CODIGO VARCHAR2(5),
    NOMBRE VARCHAR(15),
    APELLIDO VARCHAR2(15),
    SALARIO NUMBER
);

--15

ALTER TABLE EMPLEADO ADD (PUESTO VARCHAR2(1));

UPDATE EMPLEADO SET PUESTO = 'J'
WHERE SYSDATE - FECHA_NCTO < 30;

UPDATE EMPLEADO SET PUESTO = 'S'
WHERE SYSDATE - FECHA_NCTO BETWEEN 31 AND 50;

UPDATE EMPLEADO SET PUESTO = 'E'
WHERE SYSDATE - FECHA_NCTO > 50;

--16

DELETE FROM EMPLEADO
WHERE NOMBRE='SONIA' AND APELLIDO = 'LOMA';

--17

UPDATE EMPLEADO SET SALARIO = SALARIO * 0.80;

UPDATE EMPLEADO SET SALARIO = 10000
WHERE SALARIO >10000;

ALTER TABLE EMPLEADO ADD 
CONSTRAINT CK_SALARIO_EMPLEADO CHECK (SALARIO <=10000);

--18

ALTER TABLE DEPENDIENTE DROP (GENERO);

--19

ALTER TABLE EMPLEADO MODIFY (NOMBRE NOT NULL);
ALTER TABLE EMPLEADO MODIFY (APELLIDO NOT NULL);
ALTER TABLE EMPLEADO MODIFY (SALARIO NOT NULL);

--20


UPDATE empleado
SET salario = salario*0.85
WHERE cod_emp = (SELECT jefe FROM departamento WHERE cod_dep = 400);


UPDATE proyecto
SET cod_dep = 100, localiza = 'A'
WHERE cod_dep = 400;

DELETE FROM departamento WHERE cod_dep = 400;






